### ISSUE TITLE
Send manga as book chapters

### ISSUE THREAD

**Issue by palashgoel7** [aplanas/kmanga#4]
My kindle is flooded with Docs. I would be nice to send a book and keep adding chapters to it.

**Comment by aplanas** [comment]
Hi @palashgoel7!

Technically this can't be done. There is not way for kindle to add chapters to a single book or collection that was already send. Maybe I can try to group the chapters in a single volume, but this have some drawbacks: amazon limit the size of documents that you can send via email.

IMHO we can revisit this issue later, when I add mangatraders volumes to the system. But for now I will close the issue.

Thanks!

**Comment by palashgoel7** [comment]
Thanks for your views. This looks like an issue from Amazon's side. Let me see what I can do.

**Comment by aplanas** [comment]
@palashgoel7 meanwhile you can try to use collections, and add the chapter to them. I am using it to provide some sane order : )
