### ISSUE TITLE
Can't register

### ISSUE THREAD

**Issue by rohit0839** [aplanas/kmanga#7]
As a new user, can't register. It says "Whops!"

**Comment by aplanas** [comment]
What username are you registering?

**Comment by aplanas** [comment]
If your user is 'rohit', registered with a gmail account ended in ...r0, the account is there, try to login into this

**Comment by aplanas** [comment]
@rohit0839 can you confirm that you can login with `rohit` user?

**Comment by rohit0839** [comment]
Yes, I can now login.
